services:
  postgres:
    image: postgres:17

    container_name: mediflow-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kh2005@God
      POSTGRES_DB: mediflow

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: